INSERT INTO `states` VALUES (01, 'AC', 'Acre');
INSERT INTO `states` VALUES (02, 'AL', 'Alagoas');
INSERT INTO `states` VALUES (03, 'AM', 'Amazonas');
INSERT INTO `states` VALUES (04, 'AP', 'Amapá');
INSERT INTO `states` VALUES (05, 'BA', 'Bahia');
INSERT INTO `states` VALUES (06, 'CE', 'Ceará');
INSERT INTO `states` VALUES (07, 'DF', 'Distrito Federal');
INSERT INTO `states` VALUES (08, 'ES', 'Espírito Santo');
INSERT INTO `states` VALUES (09, 'GO', 'Goiás');
INSERT INTO `states` VALUES (10, 'MA', 'Maranhão');
INSERT INTO `states` VALUES (11, 'MG', 'Minas Gerais');
INSERT INTO `states` VALUES (12, 'MS', 'Mato Grosso do Sul');
INSERT INTO `states` VALUES (13, 'MT', 'Mato Grosso');
INSERT INTO `states` VALUES (14, 'PA', 'Pará');
INSERT INTO `states` VALUES (15, 'PB', 'Paraíba');
INSERT INTO `states` VALUES (16, 'PE', 'Pernambuco');
INSERT INTO `states` VALUES (17, 'PI', 'Piauí');
INSERT INTO `states` VALUES (18, 'PR', 'Paraná');
INSERT INTO `states` VALUES (19, 'RJ', 'Rio de Janeiro');
INSERT INTO `states` VALUES (20, 'RN', 'Rio Grande do Norte');
INSERT INTO `states` VALUES (21, 'RO', 'Rondônia');
INSERT INTO `states` VALUES (22, 'RR', 'Roraima');
INSERT INTO `states` VALUES (23, 'RS', 'Rio Grande do Sul');
INSERT INTO `states` VALUES (24, 'SC', 'Santa Catarina');
INSERT INTO `states` VALUES (25, 'SE', 'Sergipe');
INSERT INTO `states` VALUES (26, 'SP', 'São Paulo');
INSERT INTO `states` VALUES (27, 'TO', 'Tocantins');